name: Deploy AsyncEventApp (14_async-event-loop) In DockerHub
on:
  push:
    branches: [ main ]
    paths: ['14_async-event-loop/**']
  pull_request:
    branches: [ main ]
    paths: ['14_async-event-loop/**']
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          context: ./14_async-event-loop
          file: ./14_async-event-loop/Dockerfile
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./14_async-event-loop
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/async-event-app:latest
