name: Deploy ToDoApp (16_classes) In DockerHub
on:
  push:
    branches: [ main ]
    paths: ['16_classes/**']
  pull_request:
    branches: [ main ]
    paths: ['16_classes/**']
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          context: ./16_classes
          file: ./16_classes/Dockerfile
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./16_classes
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pairsCard:latest
