name: Deploy ObjectPrototypeApp (17_advanced-objects) In DockerHub
on:
  push:
    branches: [ main ]
    paths: ['17_advanced-objects/**']
  pull_request:
    branches: [ main ]
    paths: ['17_advanced-objects/**']
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          context: ./17_advanced-objects
          file: ./17_advanced-objects/Dockerfile
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./17_advanced-objects
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/object-prototype:latest
