name: Deploy ToDoApp (13_modules) In DockerHub
on:
  push:
    branches: [ main ]
    paths: ['13_modules/**']
  pull_request:
    branches: [ main ]
    paths: ['13_modules/**']
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          context: ./13_modules
          file: ./13_modules/Dockerfile
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./13_modules
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:latest
